<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class SkyHSHOSO_Autoloader {
    private static $class_map = array(
        'skyhshoso_uuid' => 'includes/class-skyhshoso-uuid.php',
        'skyhshoso_cart_renewal' => 'includes/class-skyhshoso-cart-renewal.php',
        'skyhshoso_hosting_detail' => 'includes/class-skyhshoso-hosting-detail.php',
        'skyhshoso_import' => 'includes/class-skyhshoso-import.php',
        'skyhshoso_subscription_functions' => 'includes/class-skyhshoso-subscription-functions.php',
        'skyhshoso_export' => 'includes/class-skyhshoso-export.php',
        'skyhshoso_zero_initial_payment_checkout_manager' => 'includes/class-skyhshoso-zero-initial-payment-checkout-manager.php',
        'skyhshoso_subscription_cron' => 'includes/class-skyhshoso-subscription-cron.php',
        'skyhshoso_subscription_db' => 'includes/class-skyhshoso-subscription-db.php',
        'skyhshoso_dashboard_shortcode' => 'includes/class-skyhshoso-dashboard-shortcode.php',
        'skyhshoso_drip_downloads_manager' => 'includes/class-skyhshoso-drip-downloads-manager.php',
        'skyhshoso_subscription_admin' => 'includes/class-skyhshoso-subscription-admin.php',
        'skyhshoso_subscription_checkout' => 'includes/class-skyhshoso-subscription-checkout.php',
        'skyhshoso_manual_renewal_manager' => 'includes/class-skyhshoso-manual-renewal-manager.php',
        'skyhshoso_menu_endpoints' => 'includes/class-skyhshoso-menu-endpoints.php',
        'skyhshoso_subscription' => 'includes/class-skyhshoso-subscription.php',
        'skyhshoso_limited_recurring_coupon_manager' => 'includes/class-skyhshoso-limited-recurring-coupon-manager.php',
        'skyhshoso_invoice' => 'includes/class-skyhshoso-invoice.php',
        'skyhshoso_emails' => 'includes/class-skyhshoso-emails.php',
        'skyhshoso_payment_gateways' => 'includes/class-skyhshoso-payment-gateways.php',
        'skyhshoso_import_export_admin' => 'includes/class-skyhshoso-import-export-admin.php',
        'skyhshoso_change_payment_gateway' => 'includes/class-skyhshoso-change-payment-gateway.php',
        'skyhshoso_early_renewal_manager' => 'includes/early-renewal/class-skyhshoso-early-renewal-manager.php',
        'skyhshoso_cart_early_renewal' => 'includes/early-renewal/class-skyhshoso-cart-early-renewal.php',
        'skyhshoso_email_new_switch_order' => 'includes/emails/class-skyhshoso-email-new-switch-order.php',
        'skyhshoso_email_completed_switch_order' => 'includes/emails/class-skyhshoso-email-completed-switch-order.php',
        'skyhshoso_admin_reports' => 'includes/admin/class-skyhshoso-admin-reports.php',
        'skyhshoso_report_upcoming_recurring_revenue' => 'includes/admin/reports/class-skyhshoso-report-upcoming-recurring-revenue.php',
        'skyhshoso_report_subscription_payment_retry' => 'includes/admin/reports/class-skyhshoso-report-subscription-payment-retry.php',
        'skyhshoso_report_subscription_events_by_date' => 'includes/admin/reports/class-skyhshoso-report-subscription-events-by-date.php',
        'skyhshoso_report_subscription_by_product' => 'includes/admin/reports/class-skyhshoso-report-subscription-by-product.php',
        'skyhshoso_report_dashboard' => 'includes/admin/reports/class-skyhshoso-report-dashboard.php',
        'skyhshoso_report_retention_rate' => 'includes/admin/reports/class-skyhshoso-report-retention-rate.php',
        'skyhshoso_report_subscription_by_customer' => 'includes/admin/reports/class-skyhshoso-report-subscription-by-customer.php',
        'skyhshoso_report_cache_manager' => 'includes/admin/reports/class-skyhshoso-report-cache-manager.php',
        'skyhshoso_subscription_line_item_switched' => 'includes/switching/class-skyhshoso-subscription-line-item-switched.php',
        'skyhshoso_order_item_pending_switch' => 'includes/switching/class-skyhshoso-order-item-pending-switch.php',
        'skyhshoso_subscription_item_fee_pending_switch' => 'includes/switching/class-skyhshoso-subscription-item-fee-pending-switch.php',
        'skyhshoso_cart_switch' => 'includes/switching/class-skyhshoso-cart-switch.php',
        'skyhshoso_subscription_item_coupon_pending_switch' => 'includes/switching/class-skyhshoso-subscription-item-coupon-pending-switch.php',
        'skyhshoso_switch_cart_item' => 'includes/switching/class-skyhshoso-switch-cart-item.php',
        'skyhshoso_subscriptions_switcher' => 'includes/switching/class-skyhshoso-subscriptions-switcher.php',
        'skyhshoso_switch_totals_calculator' => 'includes/switching/class-skyhshoso-switch-totals-calculator.php',
        'skyhshoso_add_cart_item' => 'includes/switching/class-skyhshoso-add-cart-item.php',
        'skyhshoso_paypal' => 'includes/gateways/paypal/class-skyhshoso-paypal.php',
        'skyhshoso_paypal_supports' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-supports.php',
        'skyhshoso_paypal_reference_transaction_api_response_billing_agreement' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-reference-transaction-api-response-billing-agreement.php',
        'skyhshoso_paypal_reference_transaction_api' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-reference-transaction-api.php',
        'skyhshoso_paypal_status_manager' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-status-manager.php',
        'skyhshoso_paypal_reference_transaction_api_response_checkout' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-reference-transaction-api-response-checkout.php',
        'skyhshoso_paypal_reference_transaction_api_response_recurring_payment' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-reference-transaction-api-response-recurring-payment.php',
        'skyhshoso_paypal_reference_transaction_ipn_handler' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-reference-transaction-ipn-handler.php',
        'skyhshoso_paypal_reference_transaction_api_response' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-reference-transaction-api-response.php',
        'skyhshoso_paypal_standard_change_payment_method' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-standard-change-payment-method.php',
        'skyhshoso_paypal_standard_request' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-standard-request.php',
        'skyhshoso_paypal_reference_transaction_api_request' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-reference-transaction-api-request.php',
        'skyhshoso_paypal_reference_transaction_api_response_payment' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-reference-transaction-api-response-payment.php',
        'skyhshoso_paypal_standard_switcher' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-standard-switcher.php',
        'skyhshoso_paypal_standard_ipn_handler' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-standard-ipn-handler.php',
        'skyhshoso_paypal_standard_ipn_failure_handler' => 'includes/gateways/paypal/includes/class-skyhshoso-paypal-standard-ipn-failure-handler.php',
        'skyhshoso_paypal_admin' => 'includes/gateways/paypal/includes/admin/class-skyhshoso-paypal-admin.php',
        'skyhshoso_retry_migrator' => 'includes/payment-retry/class-skyhshoso-retry-migrator.php',
        'skyhshoso_retry_table_maker' => 'includes/payment-retry/class-skyhshoso-retry-table-maker.php',
        'skyhshoso_retry_background_migrator' => 'includes/payment-retry/class-skyhshoso-retry-background-migrator.php',
        'skyhshoso_retry_manager' => 'includes/payment-retry/class-skyhshoso-retry-manager.php',
        'skyhshoso_retry' => 'includes/payment-retry/class-skyhshoso-retry.php',
        'skyhshoso_retry_rules' => 'includes/payment-retry/class-skyhshoso-retry-rules.php',
        'skyhshoso_retry_rule' => 'includes/payment-retry/class-skyhshoso-retry-rule.php',
        'skyhshoso_email_customer_payment_retry' => 'includes/payment-retry/emails/class-skyhshoso-email-customer-payment-retry.php',
        'skyhshoso_email_payment_retry' => 'includes/payment-retry/emails/class-skyhshoso-email-payment-retry.php',
        'skyhshoso_retry_email' => 'includes/payment-retry/emails/class-skyhshoso-retry-email.php',
        'skyhshoso_retry_admin' => 'includes/payment-retry/admin/class-skyhshoso-retry-admin.php',
        'skyhshoso_meta_box_payment_retries' => 'includes/payment-retry/admin/class-skyhshoso-meta-box-payment-retries.php',
        'skyhshoso_retry_stores' => 'includes/payment-retry/data-stores/class-skyhshoso-retry-stores.php',
        'skyhshoso_retry_post_store' => 'includes/payment-retry/data-stores/class-skyhshoso-retry-post-store.php',
        'skyhshoso_retry_database_store' => 'includes/payment-retry/data-stores/class-skyhshoso-retry-database-store.php',
        'skyhshoso_retry_hybrid_store' => 'includes/payment-retry/data-stores/class-skyhshoso-retry-hybrid-store.php',
        'skyhshoso_sv_api_base' => 'includes/gateways/paypal/includes/abstracts/abstract-skyhshoso-sv-api-base.php',
        'skyhshoso_retry_store' => 'includes/payment-retry/data-stores/abstract-skyhshoso-retry-store.php',
        'skyhshoso_product_shortcode' => 'includes/class-skyhshoso-product-shortcode.php',
        'skyhshoso_product_manager' => 'includes/class-skyhshoso-product-manager.php',
        'skyhshoso_server_manager' => 'includes/class-skyhshoso-server-manager.php',
		'skyhshoso_review_collector' => 'includes/class-skyhshoso-review-collector.php',
		'skyhshoso_email_campaign_db' => 'includes/class-skyhshoso-email-campaign-db.php',
		'skyhshoso_email_campaign' => 'includes/class-skyhshoso-email-campaign.php',
		'skyhshoso_email_campaign_admin' => 'includes/class-skyhshoso-email-campaign-admin.php',

        'skyhshoso_admin' => 'includes/class-skyhshoso-compat-stubs.php',
        'skyhshoso_modal' => 'includes/class-skyhshoso-compat-stubs.php',
        'skyhshoso_admin_notice' => 'includes/class-skyhshoso-compat-stubs.php',
        'skyhshoso_synchroniser' => 'includes/class-skyhshoso-compat-stubs.php',
        'skyhshoso_related_order_store' => 'includes/class-skyhshoso-compat-stubs.php',
        'skyhshoso_upgrader' => 'includes/class-skyhshoso-compat-stubs.php',
        'skyhshoso_renewal_cart_stock_manager' => 'includes/class-skyhshoso-compat-stubs.php',
        'skyhshoso_limiter' => 'includes/class-skyhshoso-compat-stubs.php',
        'skyhshoso_coupon' => 'includes/class-skyhshoso-compat-stubs.php',
        'skyhshoso_product' => 'includes/class-skyhshoso-compat-stubs.php',
        'skyhshoso_renewal_order' => 'includes/class-skyhshoso-compat-stubs.php',
        'skyhshoso_cart' => 'includes/class-skyhshoso-compat-stubs.php',
        'skyhshoso_order' => 'includes/class-skyhshoso-compat-stubs.php',
    );

    public static function init() {
        spl_autoload_register( array( __CLASS__, 'autoload' ) );
    }

    public static function autoload( $class ) {
        $class_lower = strtolower( $class );
        if ( isset( self::$class_map[ $class_lower ] ) ) {
            require_once SKYHSHOSO_PLUGIN_DIR . self::$class_map[ $class_lower ];
        }
    }
}
SkyHSHOSO_Autoloader::init();
